/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hci;

import javax.swing.ImageIcon;
import cpit380practice.*;
import java.awt.Image;
import java.util.Scanner;
import javax.swing.JTextField;


/**
 *
 * @author Win 8.1
 */
public class GrantAnItem extends javax.swing.JFrame {
     private Picture pic;
     private Item item;
      private String itemName;
       private String itemType;
       private String itemNotes;
       private People person=new People();
        Scanner input ;
    public GrantAnItem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        grantAnItemLabel = new javax.swing.JLabel();
        onlineGrantingSystemLabel2 = new javax.swing.JLabel();
        itemNameLabel2 = new javax.swing.JLabel();
        uplodeItemPicturejLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        displayPictureItem = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        notesField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        ItemNameTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ItemType = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grantAnItemLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        grantAnItemLabel.setText("Grant an item:");
        jPanel1.add(grantAnItemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        onlineGrantingSystemLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        onlineGrantingSystemLabel2.setText("ONLINE GRANTING SYSTEM");
        jPanel1.add(onlineGrantingSystemLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

        itemNameLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        itemNameLabel2.setText("Item name :");
        jPanel1.add(itemNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        uplodeItemPicturejLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        uplodeItemPicturejLabel2.setText("Item picture :");
        jPanel1.add(uplodeItemPicturejLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(displayPictureItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 160));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 200, 160));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Any notes:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 380, -1, -1));

        notesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesFieldActionPerformed(evt);
            }
        });
        jPanel1.add(notesField, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 200, 60));

        jButton1.setText("Upload");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));
        jPanel1.add(ItemNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 200, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Item type :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));
        jPanel1.add(ItemType, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 200, -1));

        Submit.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Submit.setText("Submit");
        Submit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });
        jPanel1.add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        jLabel1.setBackground(new java.awt.Color(228, 211, 205));
        jLabel1.setForeground(new java.awt.Color(228, 211, 205));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 579, 484));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String filename = FileChooser.pickAFile();
        pic = new Picture(filename);
       
        Image image = (pic.getImage());
        displayPictureItem.setIcon(new ImageIcon(image));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
         /*Readable itemNameTextField1;
        // TODO add your handling code here:
        Submit.addActionListener(al);
       itemNameTextField1=(Readable) new JTextField(16);
       itemName=itemNameTextField1.*/
        itemName=ItemNameTextField1.getText();
        itemNotes=notesField.getText();
        itemType=ItemType.getText();
        item=new Item(itemName,itemType,itemNotes,pic);
        person.addGrantItem(item);
        SuccessfullyGrantAnItem page2=new SuccessfullyGrantAnItem();
        page2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SubmitActionPerformed

    private void notesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notesFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrantAnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrantAnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrantAnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrantAnItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrantAnItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ItemNameTextField1;
    private javax.swing.JTextField ItemType;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel displayPictureItem;
    private javax.swing.JLabel grantAnItemLabel;
    private javax.swing.JLabel itemNameLabel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField notesField;
    private javax.swing.JLabel onlineGrantingSystemLabel2;
    private javax.swing.JLabel uplodeItemPicturejLabel2;
    // End of variables declaration//GEN-END:variables
}
